#                                                              -*- Makefile -*-
# Simics module makefile
#

MODULE_CLASSES = sample_i2c_device

SRC_FILES= sample-i2c-device.dml
PYTHON_FILES := module_load.py

SIMICS_API := 6
THREAD_SAFE = yes

include $(MODULE_MAKEFILE)
