#!/bin/bash
:<<'END_COMMENT'
 * This software was created by United States Government employees
 * and may not be copyrighted.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
END_COMMENT

#
# Get latest version of all cgc-monitor packages
# and update the /mnt/vmLib/cgcForensicsRepo/monitorPackages
# directory
#
here=`pwd`
export artifacts="http://127.0.0.1:8080/build-artifacts/cqe"
export DEST=/mnt/vmLib/cgcForensicsRepo/monitorPackages_cfe
export TMP=/tmp/artifacts
mkdir -p $TMP
rm -fr $TMP/*
cd $TMP
getMonitorPackage cgc-monitor-libs
getMonitorPackage cgc-monitor-utils
getMonitorPackage cgc-monitor-services
getMonitorPackage cgc-monitor-header-utils
getMonitorPackage cgc-monitor-build-utils
getMonitorPackage cgc-monitor-core
getMonitorPackage cgc-monitor-simics-scripts
cd $here
