#!/bin/bash
:<<'END_COMMENT'
 * This software was created by United States Government employees
 * and may not be copyrighted.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
END_COMMENT

exec > /tmp/getKernelSymbols.log 2>&1
uname=`uname`
nohost="-o StrictHostKeyChecking=no"
read hostIP instance < /tmp/host_ip.txt
if [ $uname == "FreeBSD" ] || [ $uname == "FreeBSD64" ]; then
   nm /boot/kernel/kernel.symbols | sort > /tmp/bsd-kernel.map
   #scp $nohost /tmp/bsd-kernel.map cgc@$hostIP:/tmp/kernel_maps/
   /tmp/simics-agent --upload /tmp/bsd-kernel.map --to /tmp/kernel_maps/bsd-kernel.map

elif [ $uname == "Linux" ] || [ $uname == "Linux64" ]; then
   #scp $nohost /boot/System.map-* cgc@$hostIP:/tmp/kerel_maps/linux-kernel.map
   cat /boot/System.map-* | sort >/tmp/System.map.sorted
   /tmp/simics-agent --upload /tmp/System.map.sorted --to /tmp/kernel_maps/linux-kernel.map
fi
echo "ready" >ack.txt
#scp $nohost ack.txt cgc@$hostIP:/mnt/simics/simicsWorkspace$instance/targetStage/
/tmp/simics-agent --upload ack.txt --to /mnt/simics/simicsWorkspace$instance/targetStage/ack.txt

