#!/bin/bash
:<<'END_COMMENT'
 * This software was created by United States Government employees
 * and may not be copyrighted.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
END_COMMENT

#
# Sometimes, the scp of a host_ip.txt file from the host to target hangs, forever.
# Might be the service node.  Might be linux.  Manifests by monitor not registering
# in the ZM l.  Run this from ZM (or individually) to kill any such.
#
PROC=$(ps aux | grep '[s]cp' | grep 'new_host_ip.txt' | grep -v tail | awk '{print $2}')
if [ $? -eq 0 ]; then
       echo killing hung scp $PROC
       if [ ! -z "$PROC" ]; then
          sudo kill $PROC
       fi
fi
PROC=$(ps aux | grep '[s]sh' | grep '/tmp/startService FROM_SNAPSHOT' | grep -v tail | awk '{print $2}')
if [ $? -eq 0 ]; then
       echo killing hung ssh $PROC
       if [ ! -z "$PROC" ]; then
          sudo kill $PROC
       fi
fi
