#!/bin/bash
:<<'END_COMMENT'
 * This software was created by United States Government employees
 * and may not be copyrighted.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
END_COMMENT

#
# NOTE, sourced by prepTarget, but run as ssh shell when as a snapshot
# and by that time, the simics agent is disabled
#
sudo rm -f /tmp/startService.log
exec >> /tmp/startService.log 2>&1
if [ "$1" == "FROM_SNAPSHOT" ]; then
    export one_box=$2
    export eth_dev=$3
    export POV=$4
fi
echo "begin startService one_box is $one_box eth_dev is $eth_dev"
mv /tmp/new_host_ip.txt /tmp/host_ip.txt
myip=`/tmp/getMyIp $eth_dev`
echo "myip is <$myip>"
if [ $one_box == "YES" ]
then
    echo "now run runOneBox.sh"
    sudo su - cgc -c "/tmp/runOneBox.sh $POV"
    echo "back from starting runOneBox.sh"
else
    if [ "$myip" == "10.10.0.100" ]
    then
        echo "now run runReplayMaster.sh"
        sudo su - cgc -c "/tmp/runReplayMaster.sh"
        echo "back from starting runReplayMaster"
    fi
    if [ "$myip" == "10.10.0.101" ]
    then
        echo "now run runIDS.sh"
        sudo su - cgc -c "/tmp/runIDS.sh $POV"
        echo "back from starting runIDS.sh"
    fi
    if [ "$myip" == "10.10.0.102" ]
    then
        echo "now run runServiceMaster.sh"
        sudo su - cgc -c "/tmp/runServiceMaster.sh"
        echo "back from starting runServiceMaster"
    fi
fi
