#!/usr/bin/python
'''
 * This software was created by United States Government employees
 * and may not be copyrighted.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
'''
import sys
import commands

def getMyIP():

    lines = commands.getoutput("/sbin/ifconfig").split("\n")
    retval = None
    for line in lines:
        #print 'line is '+line
        if line.strip().startswith('inet addr'):
            #print 'has inet addr'
            retval = line.split()[1][5:]
            break
        elif line.strip().startswith('inet '):
            #print 'has inet'
            retval = line.split()[1]
            break
    return retval

zk_hosts_file = sys.argv[1]
zk_hosts = open(zk_hosts_file, 'rb').read()
my_ip = getMyIP()
parts = zk_hosts.split(',')
index = 1
for entry in parts:
    host, port = entry.split(':')
    #print('compare %s to %s' % (host, my_ip))
    if host == my_ip:
        #print('my_ip is %s' % host)
        print index
        break
    index += 1

