#!/usr/bin/env python
#
#  Send multiple UDP packets as read from a file found
#  at /tmp/sendudp, with packets delimited by RrUdP
#
import sys
import time
import os
import socket
host = sys.argv[1].strip()
port = int(sys.argv[2].strip())
print('ip %s' % host)
print('port %d' % port)
header = None
if len(sys.argv) > 3:
    header = sys.argv[3]
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

server_addr = (host, port)
#server_addr = ('localhost', port)
infile = '/tmp/sendudp'
while True:
    try:
        sock.connect(server_addr)
        print('connect ok')
        break
    except socket.error, e:
        print('connect fail %s' % e)
        time.sleep(1)
        
    
with open (infile) as fh:
    s = fh.read()
    sock.sendall(s) 
    print('sent %d bytes' % len(s))
    got = sock.recv(1024)
    print('got %s' % got)
    time.sleep(3)
