#!/usr/bin/env python3
#
#  Send a file to a given host/port using tcp
#
import sys
import time
import os
import socket
import binascii
import logging
import logging.handlers
import argparse
import json
def getCookie(data, lgr):
    offset = data.index(b'set-cookie:') + len('set-cookie:')
    rest = data[offset:]
    lgr.debug('rest is %s' % rest)
    auth = rest.split(b'=', 1)[1]
    lgr.debug('auth is %s' % auth)
    cookie = auth.split(b';')[0]
    lgr.debug('data set cookie %s' % cookie)
    return cookie

def sendTCP(lgr):
    with open('/tmp/catchme.json', 'r') as fh:
        jdict = json.load(fh)
        if 'hang' in jdict:
            hang = jdict['hang']
        else:
            hang = False
        host = jdict['host']
        port = jdict['port']
        data = jdict['data'] 
    
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    
        server_addr = (host, port)
        while True:
            try:
                sock.connect(server_addr)
                lgr.debug('connect ok')
                break
            except(socket.error) as e:
                lgr.debug('connect fail %s' % e)
                time.sleep(1)
        #TBD REMOVE/FIX
        delim = b"\r\n\r\n"
        cookie = None
        get_next = True
        data_iter = iter(data)
        #for item in data:
        while True:
            if get_next:
                item = next(data_iter)
                if item is None:
                    lgr.debug('Got none from data iterator, break')
                    break
                item_hex = eval(item)
                item_bytes = binascii.unhexlify(item_hex)
            else:
                get_next = True
            if cookie is not None: 
                if b'Cookie:' in item_bytes:
                    lgr.debug('item has a cookie')
                    if b'RESIM_COOKIE' in item_bytes:
                        item_bytes = item_bytes.replace(b'RESIM_COOKIE', cookie)
                        lgr.debug('item is Cookie: and has a RESIM cookie, replaced with %s, item_bytes now %s' % (cookie, item_bytes))
                else:
                    if b'RESIM_COOKIE' in item_bytes:
                        item_bytes = item_bytes.replace(b'RESIM_COOKIE', cookie)
                        lgr.debug('item has a RESIM cookie, maybe in a json, replaced with %s, item_bytes now %s' % (cookie, item_bytes))
            elif b'RESIM_COOKIE' in item_bytes:
                lgr.debug('item has RESIM cookie, but no cookie has been set, do not send yet')
                #lgr.debug('item_bytes: %s' % item_bytes)
                get_next = False
            if get_next:
                sock.sendall(item_bytes) 
                lgr.debug('sent %d bytes' % len(item_bytes))
            done = False
            count = 0
            while not done:
                got = sock.recv(1024)
                lgr.debug('got len %d' % (len(got)))
                if b'set-cookie:' in got:
                    cookie = getCookie(got, lgr)
                if len(got) == 1024:
                    # dangerous assumption
                    pass
                elif len(got) > 1:
                    done = True
                    time.sleep(.1)
                else:
                    time.sleep(.1)
                    count = count+1
                    if count > 10:
                        break
        if hang:
                lgr.debug('hanging as directed')
                time.sleep(1000000)
        lgr.debug('close connection')
        sock.close()

def createNewJson(host, port, infile, hang, lgr):
    jdict = {}
    jdict['host'] = host
    jdict['port'] = port
    jdict['hang'] = hang
    with open (infile, 'r') as fh:
        tcp_json = json.load(fh)
        jdict['data']=tcp_json
    with open('/tmp/catchme.json', 'w') as fh:
        fh.write(json.dumps(jdict))

    
def main():
    parser = argparse.ArgumentParser(prog='clientTCP3', description='Send file content as TCP to a target.')
    parser.add_argument('-i', '--ip', action='store', help='IP address.')
    parser.add_argument('-p', '--port', action='store', type=int, help='Port number.')
    parser.add_argument('-f', '--file', action='store', help='Json file.')
    parser.add_argument('-g', '--hang', action='store_true', help='Hang after last send to leave connection open.')
    lgr = logging.getLogger('clientTCPlog')
    #lhStdout = lgr.handlers[0]
    lgr.setLevel(logging.DEBUG)
    fh = logging.FileHandler('/tmp/clientTCP.log')
    fh.setLevel(logging.DEBUG)
    frmt = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    fh.setFormatter(frmt)
    lgr.addHandler(fh)
    #lgr.addHandler(logging.handlers.DatagramHandler('172.20.107.155', 51010))
    #lgr.removeHandler(lhStdout)
    lgr.info('Start of log from clientTCP')
    print('begin')
    args = parser.parse_args()
    createNewJson(args.ip, args.port, args.file, args.hang, lgr)
    sendTCP(lgr)

if __name__ == '__main__':
    sys.exit(main())
