#!/usr/bin/python
import os
import sys
import socket
from monitorLibs import testRepo
from monitorLibs import szk
from monitorLibs import configMgr

'''
update a test repo (just files, no zookeeper) to include
all pov's and the first three service polls for a given CB
partialCB.py originalCB commonName topFile
'''
def listdir_fullpath(d):
    #print 'listdir_fullpath for '+d
    retval = []
    if os.path.isdir(d):
        onlyfiles = [ f for f in os.listdir(d) if os.path.isfile(os.path.join(d,f)) ]
        retval = [os.path.join(d, f) for f in onlyfiles]
    return retval

os.umask(0000)
cfg = configMgr.configMgr()
hostname = socket.gethostname()
# do zk to override cfg values from zookeeper
zk = szk.szk(hostname+"_partialCB3", cfg)
top_file = cfg.cb_dir
if len(sys.argv) == 4:
    top_file = sys.argv[3]
#print 'top_file is %s' % top_file
tr = testRepo.testRepo(top_file)
if len(sys.argv) < 2:
    print 'partialCB3 sampleName num_bins'
    exit(1)
#samples = '/mnt/vmLib/bigstuff/challenge-sets'
samples = '/mnt/vmLib/bigstuff/challenge-sets/usr/share/cgc-challenges'
cb_dir = os.path.join(samples, sys.argv[1])
path = os.path.join(cb_dir, 'poller/for-testing/')
if not os.path.exists(path):
    path = os.path.join(cb_dir, 'poller/for-release/')
polls = listdir_fullpath(path)
povs = listdir_fullpath(cb_dir+'/pov')
ids = listdir_fullpath(cb_dir+'/ids')
print ids
#cb_name = 'CB'+sys.argv[1]+sys.argv[2]
cb_name = 'CB'+sys.argv[1]+sys.argv[2]
tr.doCB(cb_name, os.path.join(cb_dir, 'bin', sys.argv[1]), polls[0:9], povs, ids, clean_dir=False)
zk.stop()
