#
# ini file for cadet01
[ENV]
RESIM_TARGET=cadet
INIT_SCRIPT=mapdriver.simics
#CREATE_RESIM_PARAMS=YES
#DRIVER_WAIT=NO
AFL_STOP_ON_READ=TRUE
AFL_BACK_STOP_CYCLES=40000000
BACK_STOP_CYCLES=9000000000

[cadet]
OS_TYPE=LINUX64
AFL_STOP_ON_READ=TRUE
RESIM_PARAM=cadet.param
SIMICS_SCRIPT=x86-x58-ich10/genx86.simics
$host_name=cadet
$use_disk2=FALSE
$use_disk3=FALSE
#$disk_image=$RESIM_IMAGE/cadet01/ubuntu24.craff
#$disk_size=2601754728
#$disk_image=newcadet/cadet.disk0.hd_image.craff
$disk_image=$RESIM_IMAGE/cadet01/cadet.disk0.hd_image.craff
$disk_size=2596515600

#$eth_dev=i82546bg
$eth_dev=i82559

$mac_address_0="00:E1:27:0F:CA:A9"
$mac_address_1="00:E1:27:0F:CA:A8"
$mac_address_2="00:1A:A0:E1:1C:9F"
$mac_address_3="00:1A:A0:E1:1C:A0"
ETH0_SWITCH=switch1
ETH1_SWITCH=switch0
RESIM_UNISTD=$RESIM_DIR/linux/ia64.tbl
RESIM_UNISTD_32=$RESIM_DIR/linux/ia32.tbl
RESIM_ROOT_PREFIX=$RESIM_IMAGE/cadet01/cadet_fs
BOOT_CHUNKS=50000000

[driver]
SIMICS_SCRIPT=x86-x58-ich10/genx86.simics
$host_name=driver
$use_disk2=FALSE
$use_disk3=FALSE
#$disk_image=$RESIM_IMAGE/driver/driver2.disk.hd_image.craff
$disk_image=$RESIM_IMAGE/driver/driver_22.disk0.hd_image.craff
$disk_size=21496236544

$mac_address_0="00:E1:27:0F:C5:A9"
$mac_address_1="00:E1:27:0F:C5:A8"
$mac_address_2="00:1A:A0:E1:15:9F"
$mac_address_3="00:1A:A0:E1:16:9F"

# Simics7 fails on the default nic
$eth_dev=i82559

ETH0_SWITCH=switch1
ETH1_SWITCH=switch0
#ETH2_SWITCH=switch0
#ETH3_SWITCH=switch0
