#!/bin/bash
:<<'END_COMMENT'
 * This software was created by United States Government employees
 * and may not be copyrighted.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
END_COMMENT
# collect together packages needed by the simulated target into a tarball
# and put it where the targets will find it.
#
here=`pwd`
targetStage=/mnt/simics/simicsWorkspace/targetStage
targetPackages_bsd=/mnt/vmLib/cgcForensicsRepo/targetPackages_cfe
targetPackages_bsd64=/mnt/vmLib/cgcForensicsRepo/targetPackages_cfe64
targetPackages_linux=/mnt/vmLib/cgcForensicsRepo/targetPackages_cfe_linux
targetPackages_linux64=/mnt/vmLib/cgcForensicsRepo/targetPackages_cfe_linux64
mkdir -p $targetStage
# clean up the target stage
rm $targetStage/*.tar
rm $targetStage/*.deb
rm $targetStage/*.gz
rm -fr $targetStage/repo/CBs

if [ -d $targetPackages_bsd ]
then
    cd $targetPackages_bsd
    tar -cvf $targetStage/targetBin_FreeBSD.tar *
else
    echo "no directory at $targetPackages_bsd"
fi
if [ -d $targetPackages_bsd64 ]
then
    cd $targetPackages_bsd64
    tar -cvf $targetStage/targetBin_FreeBSD64.tar *
else
    echo "no directory at $targetPackages_bsd64"
fi
if [ -d $targetPackages_linux ]
then
    cd $targetPackages_linux
    tar -cvf $targetStage/targetBin_Linux.tar --exclude='cgc-network-appliance*' --exclude='ethtool*' *
    cp ethtool*.deb $targetStage/ 2>/dev/null
else
    echo "no directory at $targetPackages_linux"
fi
if [ -d $targetPackages_linux64 ]
then
    cd $targetPackages_linux64
    tar -cvf $targetStage/targetBin_Linux64.tar --exclude='cgc-network-appliance*' --exclude='ethtool*' *
    cp ethtool*.deb $targetStage/ 2>/dev/null
else
    echo "no directory at $targetPackages_linux64"
fi
cd $here
