#!/bin/bash
PROC=$(ps aux | grep '[v]agrant@localhost' | grep -v tail | awk '{print $2}')
if [ -z "$PROC" ]; then
    echo "nothing trying to connect to vagrant@localhost" 
else
    echo "something trying to communicate with vagrant@localhost, running as $PROC"
    kill -9 $PROC
fi
PROC=$(ps aux | grep '[s]tartServiceOnTargets' | grep -v tail | awk '{print $2}')
if [ -z "$PROC" ]; then
    echo "no startService on targets" 
else
    echo "startServiceOnTargets, running as $PROC"
    kill -9 $PROC
fi
