#!/bin/bash
#
# Summary of monitor status in terms of game_notify/game_listener,
# the zookeeper cluster status; team set summary and monitor drones.
#
PROC=$(ps aux | grep '[g]ame_listener' | grep -v tail | awk '{print $12}')
if [ $? -eq 0 ] && [ ! -z "$PROC" ]; then
    echo "Monitor is up, watching game: "$PROC
else
   PROC=$(ps aux | grep '[g]ame_notify' | grep -v tail | awk '{print $12}')
   if [ $? -eq 0 ] && [ ! -z "$PROC" ]; then
       echo "Monitor is up, waiting for new game in: "$PROC
   else
       echo "Monitor is not runninng"
   fi
fi
echo ""
zkStatus
echo Monitor drones: `ZM l | tail -n 1`
echo ""
echo "Team sets:"
listMonitor lts not_cleared 
echo ""
echo "any critical issues will be reported below..."
ZM critical | grep -i critical
echo "End of summary"
