#!/usr/bin/python
'''
 * This software was created by United States Government employees
 * and may not be copyrighted.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
'''
'''
Mount the vmLib volume on NFS server named
as the repo_master in the configMgr

NOTE: This script is a canary, in that if it is availble on a host, then
it is assumed the host also has enough monitor support to complete a
bootstrap.  In other words, DONT MOVE THIS TO build_utils.

'''
import sys
from datetime import datetime
import socket
import subprocess
from subprocess import Popen
from monitorLibs import utils
from monitorLibs import szk
from monitorLibs import configMgr
def waitForNet(master):
     retcode = subprocess.call(['waitnet', master])

def updateTime(master):
     retcode = subprocess.call(['/usr/bin/sudo', '/usr/sbin/ntpdate', '-u', master])

hostname = socket.gethostname()
cfg = configMgr.configMgr()
# NOTE szk will cause cfg to be updated via zookeeper
print('call szk to attach zookeeper')
zk = szk.szk(hostname, cfg)
print('back from call szk to attach zookeeper')
if cfg.repo_master is None:
    print('No repo master defined, run putMonitorCfg')
    exit(1)
repo_master = cfg.repo_master
myip = utils.getMyIP()
print('using %s as repoMaster, my ip is %s' % (repo_master, myip)) 
with open('/etc/fstab', 'rb') as f_in:
   stuff = f_in.read()
   if 'vmLib' in stuff:
       print('vmLib mounted in fstab, if this is not a dev system, remove that')
       exit(0)
if myip != repo_master:
    p1 = subprocess.Popen('/bin/df', stdout = subprocess.PIPE)
    output, error = p1.communicate()
    if repo_master not in output:    
        if 'vmLib' in output:
           retcode = subprocess.call(['/usr/bin/sudo', '/bin/umount', '/mnt/vmLib'])
        waitForNet(repo_master)
        print('repo master responds to ping, mount the repo')
        source = '%s:/mnt/vmLib' % repo_master
        retcode = subprocess.call(['/usr/bin/sudo', '/bin/mount', '-o', 'nolock', '-t', 'nfs', source, '/mnt/vmLib'])
    else:
        print('vmLib mounted on proper host')
    updateTime(repo_master);
    print('back from updating time: %s' % str(datetime.now()))
else:
    print('I am the repo_master, do not try mount')

zk.stop()
