#!/usr/bin/python
'''
 * This software was created by United States Government employees
 * and may not be copyrighted.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
'''

'''
move all files from a cfe_moved_dir back to its original location
under cfe_cfg_files_dir
'''
from monitorLibs import configMgr
import os
import sys
import shutil
os.umask(0000)
def usage():
    print('resetCFE game_name')
    print('\t copy all files from the cfe_moved_dir for the given game back to their original location')
    exit(0)
if len(sys.argv) != 2:
    usage()
gname = sys.argv[1]
cfg = configMgr.configMgr()
src_dir = os.path.join(cfg.cfe_moved_dir, gname)
if not os.path.isdir(src_dir):
    print('no moved files at %s' % src_dir)
else:
    dst = os.path.join(cfg.cfe_cfg_files_dir, gname)
    flist = os.listdir(src_dir)
    for f in flist:
        src = os.path.join(src_dir, f)
        print('copy %s to %s' % (src, dst))
        shutil.copyfile(src, os.path.join(dst, f))
    shutil.rmtree(src_dir)
done_dir = os.path.join(cfg.cfe_done_files_dir, gname)
try:
    shutil.rmtree(done_dir)
except:
    pass
print('reset game %s' % gname)

