#!/usr/bin/python
'''
 * This software was created by United States Government employees
 * and may not be copyrighted.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
'''
import socket
from monitorLibs import configMgr
from monitorLibs import szk
import os
import time
import sys
'''
Shutdown the monitors on a host.
First delete the configuration node to signal the targets to copy their logs to the host.
Then use the service "clean".
If an instance is given, just delete that configuration node
'''
hostname = socket.gethostname()
cfgfile = configMgr.configMgr()
cmd = 'killPutCfg'
os.system(cmd)
if len(sys.argv) > 1 and sys.argv[1] != 'spare_the_watcher':
    instance = sys.argv[1]
    zk = szk.szk(hostname, cfgfile, instance, wait_for_zk=False)
    if zk.zk is not None:
        zk.deleteReplayCFG(False)
else:
    if len(sys.argv) < 2 or sys.argv[1] != 'spare_the_watcher':
        os.system('killMonitorWatcher')
    zk = szk.szk(hostname, cfgfile, wait_for_zk=False)
    if zk.zk is not None:
        zk.deleteReplayCFG(True)
        time.sleep(10)
    cmd = 'sudo /etc/init.d/monitorSlaveService clean'
    os.system(cmd)
    # get rid of any hackStdIn shells and pipes
    cmd = 'clearStdIn'
    os.system(cmd)
    cmd = 'killVagrantTalkers'
    os.system(cmd)
zk.stop()
