#!/bin/bash
:<<'END_COMMENT'
 * This software was created by United States Government employees
 * and may not be copyrighted.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
END_COMMENT
#
# Fix the POS that is Wind River's LM "lmgrd"
#
here=`pwd`
# simics lmgrd has path issues, make sure we are not in a workspace
cd /tmp
if [ -z "$SIMDIR" ]
then
    export SIMDIR=/mnt/simics/simics-4.8/simics-4.8.170
    echo SIMDIR environment variable not defined
    echo use $SIMDIR

fi
myLicenses=/mnt/re_images/licenses
myMAC=`/sbin/ifconfig | grep eth0 | awk '{print $5;}' | tr : _`
echo myMAC is $myMAC
myFile=ConsolidatedLicenseFile-$myMAC.lic
if [ ! -f "$myLicenses/$myFile" ]; then
    echo "no file at ""$myLicenses/$myFile" "try alternate"
    myMAC=`/sbin/ifconfig | grep eth0 | awk '{print toupper($5);}' | sed s/://g`
    echo myMAC is $myMAC
    myFile=$myMAC.lic
    if [ ! -f "$myLicenses/$myFile" ]; then
# WR not consistent in filenames...
        wrdumb=$myMAC.txt
        if [ -f "$myLicenses/$wrdumb" ]; then
            mv "$myLicenses/$wrdumb" "$shareLicenses/$myFile"
        fi
    fi
fi
if [ ! -f "$myLicenses/$myFile" ]; then
    echo "could not find license file for " $myFile
    echo "exiting"
    exit
fi    
echo "Kill & recreate the lmgrd unstable garbage license manager"
PROC=$(ps aux | grep '[l]mgrd' | grep -v Fix| grep -v tail | awk '{print $2}')
if [ $? -eq 0 ]; then
    echo lmgrd proc to kill is $PROC
    if [ ! -z "$PROC" ]; then
       kill $PROC
    fi
fi 
sleep 2
sudo mkdir -p /usr/tmp/.flexlm
sudo chmod a+rw -R /usr/tmp/.flexlm
export PATH=$PATH:/mnt/simics/simics-4.8/simics-4.8.125/flexnet/linux64/bin
echo "path is $PATH"
$SIMDIR/flexnet/linux64/bin/lmgrd -c $myLicenses/$myFile
echo "$SIMDIR/flexnet/linux64/bin/lmgrd -c $myLicenses/$myFile"

