#! /bin/sh
# /etc/init.d/initReplay
### BEGIN INIT INFO
# Provides:          initReplay
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: cgc target replay management
# Description:       see short
### END INIT INFO

# Start a replay service on a simulated target

case "$1" in
  start)
    echo "Starting replay from init.d"
    su - cgc -c runReplayMaster.sh &
    ;;
  restart)
    echo "no such command, needed for lintian"
    ;;
  force-reload)
    echo "no such command, needed for lintian"
    ;;
  stop)
    echo "Stopping replay"
    pkill replay_master
    ;;
  *)
    echo "Usage: /etc/init.d/initReplay {start|stop}"
    exit 1
    ;;
esac

exit 0
