#! /bin/sh
# /etc/init.d/logUpdateService
### BEGIN INIT INFO
# Provides:          logUpdateService
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: update sql as replays finish
# Description:       see short
### END INIT INFO

# Start zookeeper 
umask 000
case "$1" in
  start)
    exec >> /tmp/logUpdateService.log 2>&1
    echo "Starting updateDBLogs from init.d"
    su mike -c 'updateDBLogs' &
    ;;
  stop)
    echo "Stopping updateDBLogs"
    su mike -c 'pkill updateDBLogs'
    ;;
  restart)
    echo "Restarting updateDBLogs"
    su mike -c 'pkill updateDBLogs'
    su mike -c 'updateDBLogs' &
    ;;
  force-reload)
    echo "not supported"
    ;;
  *)
    echo "Usage: /etc/init.d/logUpdateService {start|stop}"
    exit 1
    ;;
esac

exit 0

