#! /bin/sh
# /etc/init.d/sqlUpdateService
### BEGIN INIT INFO
# Provides:          sqlUpdateService
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: update databases as team sets finish
# Description:       see short
### END INIT INFO

# Start zookeeper 
umask 000
case "$1" in
  start)
    exec >> /tmp/sqlUpdateService.log 2>&1
    echo "Starting updateSQL from init.d param is $2"
    su mike sh -c "updateSQL $2" &
    ;;
  restart)
    echo 'restarting updateSQL'
    su mike -c 'pkill updateSQL'
    su mike sh -c "updateSQL $2" &
    ;;
  force-reload)
    echo "not supported"
    ;;
  stop)
    echo "Stopping updateSQL"
    su mike -c 'pkill updateSQL'
    ;;
  *)
    echo "Usage: /etc/init.d/sqlUpdateService {start|stop}"
    exit 1
    ;;
esac

exit 0

