#!/bin/bash
sudo umount /mnt/data
PROC=$(ps aux | grep '[K]ageNet' | grep -v tail | awk '{print $2}')
if [ $? -eq 0 ]; then
    echo ssh proc to kill is $PROC
    if [ ! -z "$PROC" ]; then
       sudo kill $PROC
    fi
fi

