#! /bin/sh
# /etc/init.d/zkShellService
### BEGIN INIT INFO
# Provides:          zkShellService
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: cgc zookeeper shell target
# Description:       think parallel ssh
### END INIT INFO

# Start the zookeeper client
CGC=/mnt/cgc
ZK=/mnt/cgc/zk/zkShell
case "$1" in
  start)
    exec >> /tmp/zkShell.log 2>&1
    echo "Starting zkShell from init.d"
    cd $ZK/bin
    su mike -c './startZshell.sh' &
    ;;
  stop)
    echo "Stopping monitor slave"
    kill $(ps aux | grep '[s]tartZshell.sh' | grep -v tail | awk '{print $2}')
    kill $(ps aux | grep '[z]kShell' | grep -v tail | awk '{print $2}')

    ;;
  force-reload)
    echo "just here cause debian thinks the world of it"
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: /etc/init.d/zkShellService.sh {start|stop|restart}"
    exit 1
    ;;
esac

exit 0


