#!/bin/bash
#
# remove pipe used as stdin for simics, and kill keep-open processes
#
rm -f /mnt/simics/simicsWorkspace*/simics.stdin
PROC=$(ps aux | grep '[h]ackStdIn' | grep -v tail | awk '{print $2}')
if [ -z "$PROC" ]; then
    echo no hackStdIn
else
    echo "hackStdIn running as $PROC"
    kill -9 $PROC
fi
