#!/bin/bash
#
# kill simics monitor related processes for a given workspace number.
# Intended for use in testing and on-off debug monitors.
#
if [ -z $1 ]; then
    echo "killSimicsWorkspace number"
    exit
fi
PROC=$(ps aux | grep '[s]imics-common' | grep -v tail | grep simicsWorkspace$1 | awk '{print $2}')
if [ -z "$PROC" ]; then
    echo no simics common running at simicsWorkspace$1
else
    echo "simics-common for $1 running as $PROC"
    kill -9 $PROC
fi

PROC=$(ps aux | grep '[p]utPackages' | grep "[p]utPackages $1" |  grep -v tail | awk '{print $2}')
if [ -z "$PROC" ]; then
    echo no putPackages running at simicsWorkspace$1
else
    echo "putPackages for $1 running as $PROC"
    kill -9 $PROC
fi
