#!/bin/bash
#
# kill simics monitor related processes for a given workspace number.
# Intended for use in testing and on-off debug monitors.
#
if [ -z $1 ]; then
    echo "killPortListener port"
    exit
fi
PROC=$(lsof -i tcp:$1 | awk '{print $2}')
if [ -z "$PROC" ]; then
    echo no listener at $1
else
    echo "listening at $1"
    for proc in $PROC; do
        if [ $proc != "PID" ]; then
            echo $proc
            kill -9 $proc
        fi
    done
fi

