#!/bin/bash
#
# Send a simics command to a workspace via its simics.stdin pipe
# First get its attention with a INT signal
#
if [ -z $1 ]; then
    echo "send SimicsWorkspace number command"
    exit
fi
PROC=$(ps aux | grep '[s]imics-common' | grep -v tail | grep simicsWorkspace$1 | awk '{print $2}')
if [ -z "$PROC" ]; then
    echo no simics common running at simicsWorkspace$1
else
    echo "simics-common for $1 running as $PROC"
    kill -s INT $PROC
    echo "$2" >>/mnt/simics/simicsWorkspace$1/simics.stdin
    echo "echo $2 >>/mnt/simics/simicsWorkspace$1/simics.stdin"
    sleep 2
    tail /mnt/cgc/logs/monitor*$1.log
fi
